apiVersion: batch/v1
kind: Job
metadata:
  name: database-backup-job
  namespace: production
spec:
  template:
    spec:
      containers:
      - name: postgres-backup
        image: postgres:13-alpine
        command:
        - /bin/bash
        - -c
        - |
          pg_dump $DATABASE_URL > /backup/db_backup_$(date +%Y%m%d_%H%M%S).sql
          echo "Backup completed successfully"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DATABASE_URL
        volumeMounts:
        - name: backup-storage
          mountPath: /backup
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: backup-pvc
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: database-backup-cronjob
  namespace: production
spec:
  schedule: "0 2 * * *" # Every day at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: postgres:13-alpine
            command:
            - /bin/bash
            - -c
            - |
              BACKUP_FILE="/backup/db_backup_$(date +%Y%m%d_%H%M%S).sql"
              pg_dump $DATABASE_URL > $BACKUP_FILE

              # Keep only last 7 days of backups
              find /backup -name "db_backup_*.sql" -mtime +7 -delete

              echo "Backup completed: $BACKUP_FILE"
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DATABASE_URL
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: production
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 5Gi
