apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: production
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM= # password123
  DATABASE_URL: cG9zdGdyZXM6Ly9hcHB1c2VyOnBhc3N3b3JkMTIzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9teWFwcA==
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: production
type: Opaque
data:
  JWT_SECRET: bXlzdXBlcnNlY3JldGp3dGtleQ== # mysupersecretjwtkey
  API_KEY: YWJjZGVmZ2hpams= # abcdefghijk
  REDIS_PASSWORD: cmVkaXNwYXNz # redispass
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: production
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3MiLCJhdXRoIjoiZFhObGNqcHdZWE56In19fQ==
